In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.0.0


## 4.5.1 load and save NDarray

In [2]:
import numpy as np

x = tf.ones(3)
x

<tf.Tensor: id=2, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [3]:
np.save('x.npy', x)
x2 = np.load('x.npy')
x2

array([1., 1., 1.], dtype=float32)

In [4]:
y = tf.zeros(4)
np.save('xy.npy',[x,y])
x2, y2 = np.load('xy.npy', allow_pickle=True)
(x2, y2)

(<tf.Tensor: id=6, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Tensor: id=7, shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [5]:
mydict = {'x': x, 'y': y}
np.save('mydict.npy', mydict)
mydict2 = np.load('mydict.npy', allow_pickle=True)
mydict2

array({'x': <tf.Tensor: id=8, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>, 'y': <tf.Tensor: id=9, shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>},
      dtype=object)

## 4.5.2 load and save model parameters

In [6]:
X = tf.random.normal((2,20))
X

<tf.Tensor: id=15, shape=(2, 20), dtype=float32, numpy=
array([[ 5.9130055e-01, -5.5540323e-01,  6.5195680e-01,  1.0148551e+00,
         1.1653853e-01,  3.4088513e-01, -1.9349420e+00,  2.3217506e+00,
        -1.3243454e+00,  7.8213990e-01, -3.0135760e-01,  7.1492398e-01,
         2.0329635e+00, -9.9247020e-01, -1.3943609e+00,  3.0341945e+00,
         1.0853903e+00,  1.7853489e+00,  6.9328678e-01, -5.1030307e-03],
       [ 1.3758225e+00, -6.2940782e-01, -2.8039312e-01, -1.7644655e+00,
        -1.0396123e+00, -4.5697919e-01, -6.7717117e-01, -1.2451811e+00,
        -9.8004079e-01,  1.8818023e-02, -6.8302959e-01, -6.5864509e-01,
         2.8474357e-03,  1.6101544e+00, -1.0211481e+00,  6.8822199e-01,
        -1.6048189e+00,  4.1619232e-01,  4.2764521e-01, -2.8804401e-01]],
      dtype=float32)>

In [7]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()    # Flatten层将除第一维（batch_size）以外的维度展平
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = self.dense1(x)    
        output = self.dense2(x)     
        return output

net = MLP()
Y = net(X)
Y

<tf.Tensor: id=71, shape=(2, 10), dtype=float32, numpy=
array([[-0.57706153,  0.5499399 , -0.5188131 , -0.44329253, -0.18954232,
        -0.01476651,  1.0588677 , -0.5438232 ,  0.24462904,  0.02958708],
       [ 0.03182643, -0.32062384,  0.21857792,  0.12499061, -0.449143  ,
         0.61017936,  0.25954786, -0.5927453 , -0.08654066, -0.3091799 ]],
      dtype=float32)>

In [8]:
net.save_weights("4.5saved_model.h5")

In [9]:
net2 = MLP()
net2.load_weights("4.5saved_model.h5")
Y2 = net2(X)
Y2 == Y

ValueError: You are trying to load a weight file containing 2 layers into a model with 0 layers.