In [2]:
import tensorflow as tf
print(tf.__version__)

D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\dev_tools\Anaconda3_2019.07\envs\tens

2.0.0-alpha0


D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\dev_tools\Anaconda3_2019.07\envs\tensorflow\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\dev_tools\Anacon

## 2.2.1 Create NDArray

In [40]:
x = tf.constant(range(12))

In [41]:
x

<tf.Tensor: id=91, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [42]:
x.shape

TensorShape([12])

In [43]:
len(x)

12

In [44]:
X = tf.reshape(x,(3,4))

In [45]:
tf.zeros((2,3,4))

<tf.Tensor: id=97, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [46]:
tf.ones((3,4))

<tf.Tensor: id=101, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [35]:
Y = tf.constant([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

<tf.Tensor: id=69, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

In [38]:
tf.random.normal(shape=[3,4], mean=0, stddev=1)

<tf.Tensor: id=89, shape=(3, 4), dtype=float32, numpy=
array([[-1.8919201 ,  0.69319326, -1.242913  , -0.6050978 ],
       [ 0.1156491 ,  0.6371175 ,  0.81829435,  0.35308817],
       [-0.09551748, -1.820314  ,  1.1715374 , -1.9139055 ]],
      dtype=float32)>

## 2.2.2 arithmetic ops

In [47]:
X + Y

<tf.Tensor: id=103, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [48]:
X * Y

<tf.Tensor: id=105, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [55]:
X / Y

<tf.Tensor: id=117, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [59]:
Y = tf.cast(Y, tf.float32)
tf.exp(Y)

<tf.Tensor: id=123, shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.598152 , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

In [63]:
Y = tf.cast(Y, tf.int32)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: id=130, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])>

In [69]:
tf.concat([X,Y],axis = 0), tf.concat([X,Y],axis = 1)

(<tf.Tensor: id=136, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])>,
 <tf.Tensor: id=138, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])>)

In [74]:
tf.equal(X,Y)

<tf.Tensor: id=144, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [76]:
tf.reduce_sum(X)

<tf.Tensor: id=147, shape=(), dtype=int32, numpy=66>

In [85]:
X = tf.cast(X, tf.float32)
tf.norm(X)

<tf.Tensor: id=176, shape=(), dtype=float32, numpy=22.494444>

## 2.2.3 broadcasting

In [88]:
A = tf.reshape(tf.constant(range(3)), (3,1))
B = tf.reshape(tf.constant(range(2)), (1,2))
A, B

(<tf.Tensor: id=184, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: id=187, shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [89]:
A + B

<tf.Tensor: id=190, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [90]:
## 2.2.4 indexing

In [91]:
X[1:3]

<tf.Tensor: id=195, shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [96]:
X = tf.Variable(X)
X[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [117]:
X = tf.Variable(X)
X

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])>

In [119]:
X[1:2,:].assign(tf.ones(X[1:2,:].shape, dtype = tf.int32))

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 1,  1,  1,  1],
       [ 8,  9, 10, 11]])>

In [101]:
## 2.2.5 saving memory

In [106]:
X = tf.cast(X, tf.int32)
before = id(Y)
Y = Y + X
id(Y) == before

False

In [110]:
Z = tf.Variable(tf.zeros_like(Y))
before = id(Z)
Z[:].assign(X + Y)
id(Z) == before

True